### ISSUE TITLE
Add more example code and docs

### ISSUE THREAD

**Issue by sideshow** [sideshow/apns2#54]
- [ ] Examples of how to use with go channels and go routines
- [ ] Document Client timeout behaviour (issue #24)
- [ ] Document ClientManager and concurrent access safety (issue #44)
- [ ] Document Generating correct .pem/p12 certificates (issue #33 and issue #46)
